// Code generated by "gocqlx/cmd/schemagen"; DO NOT EDIT.

package schemagentest

import (
	"github.com/apache/cassandra-gocql-driver/v2"
	"github.com/playneta/gocqlx/v3"
	"github.com/playneta/gocqlx/v3/table"
)

// Table models.
var (
	Playlists = table.New(table.Metadata{
		Name: "playlists",
		Columns: []string{
			"album",
			"artist",
			"id",
			"song_id",
			"title",
		},
		PartKey: []string{
			"id",
		},
		SortKey: []string{
			"title",
			"album",
			"artist",
		},
	})

	Songs = table.New(table.Metadata{
		Name: "songs",
		Columns: []string{
			"album",
			"artist",
			"data",
			"duration",
			"id",
			"tags",
			"title",
		},
		PartKey: []string{
			"id",
		},
		SortKey: []string{},
	})
)

// User-defined types (UDT) structs.
type AlbumUserType struct {
	gocqlx.UDT
	Name        string
	Songwriters []string
}

// Table structs.
type PlaylistsStruct struct {
	Album  AlbumUserType
	Artist string
	Id     [16]byte
	SongId [16]byte
	Title  string
}
type SongsStruct struct {
	Album    string
	Artist   string
	Data     []byte
	Duration gocql.Duration
	Id       [16]byte
	Tags     []string
	Title    string
}
